// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

public type ConversionResult record {
    # ISO 4217 currency code converted from
    string sourceCurrency;
    # original amount in the source currency
    decimal amount;
    # exchange rate applied (source currency to USD)
    decimal rate;
    # resulting amount in USD
    decimal convertedAmount;
    # always USD
    string targetCurrency;
    # when the applied rate was last updated by the provider
    string rateTimestamp;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type ConversionRequest record {
    # ISO 4217 currency code to convert from
    string sourceCurrency;
    # amount in the source currency
    decimal amount;
};

public type ConversionResultOk record {|
    *http:Ok;
    ConversionResult body;
|};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
